language: python
python:
- '3.6'
- '3.7'
install:
- pip install setuptools --upgrade
- python setup.py install
script:
- python -m unittest tests/*.py
notifications:
  email: false
deploy:
  provider: pypi
  user: hidekuma
  skip_existing: true
  distributions: "sdist bdist_wheel"
  password:
    secure: Op/o07KbKlFgnl6SziTwLt0pgx546Qudfb/jHd+SBAuuNnHYiks9eLEHHiVMaP2BFKgT6GvgUpQjaHmNcKY7O8QBAI6voRZb0V07C+UTNHBesYpM8O1z/C+jVusvMgysoHSEUuzz7/TNhpc2cQTZ0C1EVU3IaEeUd0d0rXEQ+qE1SR5cXWeGTJ5It7IvhyrlnLu30r1aWHWAaCBuYcIDqC51tldA5EgMceEBlERZxe/ZgUt3eWmla9gVJkOGnuSCgBpq/K3iS/T5KWH8NcbrbvvvYTx93Yz4SJPYCFojrmOIJvpn6sPaFAORwx6M9lc7DUphG0/c4mTpFNt+zaT76oBazCcpDEpnVKhquZtAlHNCOGOb4JpSr4hQFQj8HckfYaiL4kZzyqErW8MRZSWVoNs3HFXru9VVuDAETGvWuWU4TFQHWTyLcPDM2brJsUxLik2tv1CGNXz8QJ+6F7CYh4pLkrQGMIfqyVUTb/7nT/1/Q4vrwVvwxUuCZWsy2XIha5wenkznzSsP5GFZyCygIxByf3F0WmLq1quhRLvuuGLNHRu50nx9Ad10tg7saddDMmDMplNW0ae3xi4rdWAe5uc4pZcxukLOTPjj9I+vAomSQ1FwJEjqHYrJYvlWb5y8bNJT6dsMHjcPN6XKSUh1wP5cl7oPNvicz5Qh9Mfm+QA=
